// <auto-generated />
using EvTecnicaGyS.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EvTecnicaGyS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EvTecnicaGyS.Domain.Models.Client", b =>
                {
                    b.Property<string>("CodCliente")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CodigoSAP")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("GrupoFacturacion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InactivoDesde")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreCorto")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.HasKey("CodCliente");

                    b.ToTable("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
